version: "3.7"

services:
  security-jwt-db:
    image: mysql:8
    container_name: security-jwt-db
    environment:
      MYSQL_ROOT_PASSWORD: password3892
      MYSQL_DATABASE: springSecurityJWT
    ports:
        - "3307:3306"
    volumes:
      - spring-security-jwt-db:/var/lib/mysql

volumes:
  spring-security-jwt-db: